/**
 * Cooldown for unauthenticated endpoints that fan out to external APIs.
 *
 * `seed.searchCandidates` issues up to five OpenAlex queries per call and needs no account,
 * so it is the cheapest endpoint to abuse. The guest key is generated by the client and can
 * be rotated freely, so it only stops accidental hammering; the network address is the part
 * that actually costs an abuser something.
 *
 * State lives in this process. The app ships as a single Node bundle, so that is accurate
 * today; behind more than one instance this becomes per-instance and needs a shared store.
 */

export const SEARCH_COOLDOWN_MS = 60_000;

export type CooldownDecision =
  | { allowed: true }
  | { allowed: false; retryAfterSeconds: number };

export type CooldownStore = Map<string, number>;

/** Pure decision step, separated from the module store so it can be tested directly. */
export function evaluateCooldown(
  store: CooldownStore,
  keys: readonly string[],
  now: number,
  windowMs: number
): CooldownDecision {
  let longestWait = 0;
  for (const key of keys) {
    const last = store.get(key);
    if (last === undefined) continue;
    const elapsed = now - last;
    if (elapsed < windowMs)
      longestWait = Math.max(longestWait, windowMs - elapsed);
  }
  if (longestWait > 0) {
    return { allowed: false, retryAfterSeconds: Math.ceil(longestWait / 1000) };
  }
  return { allowed: true };
}

/** Records a successful pass and drops entries that can no longer block anything. */
export function commitCooldown(
  store: CooldownStore,
  keys: readonly string[],
  now: number,
  windowMs: number
) {
  // Array.from keeps this compatible with the project's downlevel iteration target.
  for (const [key, last] of Array.from(store.entries())) {
    if (now - last >= windowMs) store.delete(key);
  }
  for (const key of keys) store.set(key, now);
}

const searchCooldownStore: CooldownStore = new Map();

/** Reads the caller's address, preferring the proxy header Express itself would use. */
export function requestAddress(req: {
  ip?: string;
  headers?: Record<string, unknown>;
  socket?: { remoteAddress?: string };
}): string {
  const forwarded = req.headers?.["x-forwarded-for"];
  const firstHop =
    typeof forwarded === "string"
      ? forwarded.split(",")[0]?.trim()
      : Array.isArray(forwarded)
        ? String(forwarded[0]).split(",")[0]?.trim()
        : undefined;
  return firstHop || req.ip || req.socket?.remoteAddress || "unknown";
}

/**
 * Throws a user-facing Korean error when the caller is still inside the cooldown window,
 * otherwise records the attempt and returns.
 */
export function enforceSearchCooldown(
  guestKey: string,
  address: string,
  now = Date.now(),
  store: CooldownStore = searchCooldownStore
) {
  const keys = [`guest:${guestKey}`, `addr:${address}`];
  const decision = evaluateCooldown(store, keys, now, SEARCH_COOLDOWN_MS);
  if (!decision.allowed) {
    throw new Error(
      `외부 논문 검색은 ${SEARCH_COOLDOWN_MS / 1000}초에 한 번만 실행할 수 있습니다. ${decision.retryAfterSeconds}초 후 다시 시도해 주세요.`
    );
  }
  commitCooldown(store, keys, now, SEARCH_COOLDOWN_MS);
}
